# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: install all dependencies
      run: |
        go version
        go get -u github.com/gin-gonic/gin

    - name: Building the instagram-app
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      
    - name: Testing the instagram-app
      run: go test -v ./...
      
      
  deploy: # deploy on docker hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push to docker hub registery
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: instagram-service
