# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build: # building the application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: install all dependencies
      run: |
        go version
        go get -u github.com/gin-gonic/gin

    - name: Building the instagram-app
      run: go build -v ./...

  test: # testing the application
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      
    - name: Testing the instagram-app
      run: go test -v ./...
      
      
  instagram-service-image: # push instagram-service image on docker hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push to docker hub registery
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: instagram-service


  deploy:
      runs-on: ubuntu-latest
      needs: [build]
      environment:
        name: production
      steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: deploying to Heroku
          uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
        - name: create repo on heroku named instagram-app
          run: heroku create instagram-app