# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: install all dependencies
      run: |
        go version
        go get -u github.com/gin-gonic/gin

    - name: Building the instagram-app
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      
    - name: Testing the instagram-app
      run: go test -v ./...
